// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiH4ajQRf9rPxMUBml2OHl5Bh0qPaL0O0',
    appId: '1:275754738221:web:1adcedea494b9bd6f60ea4',
    messagingSenderId: '275754738221',
    projectId: 'controlmantenimientounj',
    authDomain: 'controlmantenimientounj.firebaseapp.com',
    storageBucket: 'controlmantenimientounj.firebasestorage.app',
    measurementId: 'G-2KD25TF0KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_5NYm4ljz-MC9WzlqhOrA905UwpQHROM',
    appId: '1:275754738221:android:e5621a257e73d2f1f60ea4',
    messagingSenderId: '275754738221',
    projectId: 'controlmantenimientounj',
    storageBucket: 'controlmantenimientounj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA39eqBdQG7d_wy_KOCH8i5nprqflKphnk',
    appId: '1:275754738221:ios:31d8a3e855605343f60ea4',
    messagingSenderId: '275754738221',
    projectId: 'controlmantenimientounj',
    storageBucket: 'controlmantenimientounj.firebasestorage.app',
    iosBundleId: 'com.example.appmantflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA39eqBdQG7d_wy_KOCH8i5nprqflKphnk',
    appId: '1:275754738221:ios:31d8a3e855605343f60ea4',
    messagingSenderId: '275754738221',
    projectId: 'controlmantenimientounj',
    storageBucket: 'controlmantenimientounj.firebasestorage.app',
    iosBundleId: 'com.example.appmantflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiH4ajQRf9rPxMUBml2OHl5Bh0qPaL0O0',
    appId: '1:275754738221:web:4fa1121fc95d3ac8f60ea4',
    messagingSenderId: '275754738221',
    projectId: 'controlmantenimientounj',
    authDomain: 'controlmantenimientounj.firebaseapp.com',
    storageBucket: 'controlmantenimientounj.firebasestorage.app',
    measurementId: 'G-G6NFR67J57',
  );
}
